<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://www.royalihc.com/Middleware/Services/NestixReceiveMaterialService/ReceiveMaterial">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ReceiveMaterial.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root" namespace=""/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ReceiveMaterial.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root" namespace=""/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON MAY 20 11:47:39 CEST 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <Root>
         <MsgSeqNo>
            <xsl:value-of select="/Root/MsgSeqNo"/>
         </MsgSeqNo>
         <Sender>
            <xsl:value-of select="/Root/Sender"/>
         </Sender>
         <DateTime>
            <xsl:value-of select="/Root/DateTime"/>
         </DateTime>
         <xsl:for-each select="/Root/PurchaseOrder">
            <PurchaseOrder>
               <IFS_PONumber>
                  <xsl:value-of select="IFS_PONumber"/>
               </IFS_PONumber>
               <SPx_PONumber>
                  <xsl:value-of select="SPx_PONumber"/>
               </SPx_PONumber>
               <SupplierNumber>
                  <xsl:value-of select="SupplierNumber"/>
               </SupplierNumber>
               <xsl:for-each select="PurchaseOrderLine">
                  <PurchaseOrderLine>
                     <IFS_POLNumber>
                        <xsl:value-of select="IFS_POLNumber"/>
                     </IFS_POLNumber>
                     <SPx_POLNumber>
                        <xsl:value-of select="SPx_POLNumber"/>
                     </SPx_POLNumber>
                     <CertificateClass>
                        <xsl:value-of select="CertificateClass"/>
                     </CertificateClass>
                     <Certificate>
                        <xsl:value-of select="Certificate"/>
                     </Certificate>
                     <CarbonEquivalent>
                        <xsl:value-of select="CarbonEquivalent"/>
                     </CarbonEquivalent>
                     <SurfaceTreatment>
                        <xsl:value-of select="SurfaceTreatment"/>
                     </SurfaceTreatment>
                     <CoatingCertificate>
                        <xsl:value-of select="CoatingCertificate"/>
                     </CoatingCertificate>
                     <MechanicalTest>
                        <xsl:value-of select="MechanicalTest"/>
                     </MechanicalTest>
                     <xsl:for-each select="Plate">
                        <Plate>
                           <ProjectNumber>
                              <xsl:value-of select="ProjectNumber"/>
                           </ProjectNumber>
                           <Nestix_Section_ID>
                              <xsl:value-of select="Nestix_Section_ID"/>
                           </Nestix_Section_ID>
                           <Nestix_Du_ID>
                              <xsl:value-of select="Nestix_Du_ID"/>
                           </Nestix_Du_ID>
                           <ArticleNumber>
                              <xsl:value-of select="ArticleNumber"/>
                           </ArticleNumber>
                           <WantedDeliveryDate>
                              <xsl:value-of select="WantedDeliveryDate"/>
                           </WantedDeliveryDate>
                           <PlateNumber>
                              <xsl:value-of select="PlateNumber"/>
                           </PlateNumber>
                           <Quantity>
                              <xsl:value-of select="Quantity"/>
                           </Quantity>
                           <IFS_Release_Nr>
                              <xsl:value-of select="IFS_Release_Nr"/>
                           </IFS_Release_Nr>
                           <Weight>
                              <xsl:value-of select="Weight"/>
                           </Weight>
                           <ReceivedWeight>
                              <xsl:value-of select="ReceivedWeight"/>
                           </ReceivedWeight>
                           <ReceivingDate>
                              <xsl:value-of select="ReceivingDate"/>
                           </ReceivingDate>
                           <HeatNo>
                              <xsl:value-of select="HeatNo"/>
                           </HeatNo>
                           <Length>
                              <xsl:value-of select="Length"/>
                           </Length>
                           <Width>
                              <xsl:value-of select="Width"/>
                           </Width>
                           <Info>
                              <xsl:value-of select="Info"/>
                           </Info>
                           <CertificateType>
                              <xsl:value-of select="CertificateType"/>
                           </CertificateType>
                           <CertificateNumber>
                              <xsl:value-of select="CertificateNumber"/>
                           </CertificateNumber>
                           <CarbonEquivalent>
                              <xsl:value-of select="CarbonEquivalent"/>
                           </CarbonEquivalent>
                           <SurfaceTreatment>
                              <xsl:value-of select="SurfaceTreatment"/>
                           </SurfaceTreatment>
                           <CoatingCertificate>
                              <xsl:value-of select="CoatingCertificate"/>
                           </CoatingCertificate>
                           <MechanicalTest>
                              <xsl:value-of select="MechanicalTest"/>
                           </MechanicalTest>
                        </Plate>
                     </xsl:for-each>
                     <xsl:for-each select="Profile">
                        <Profile>
                           <ProjectNumber>
                              <xsl:value-of select="ProjectNumber"/>
                           </ProjectNumber>
                           <Nestix_Section_ID>
                              <xsl:value-of select="Nestix_Section_ID"/>
                           </Nestix_Section_ID>
                           <Nestix_Du_ID>
                              <xsl:value-of select="Nestix_Du_ID"/>
                           </Nestix_Du_ID>
                           <ArticleNumber>
                              <xsl:value-of select="ArticleNumber"/>
                           </ArticleNumber>
                           <WantedDeliveryDate>
                              <xsl:value-of select="WantedDeliveryDate"/>
                           </WantedDeliveryDate>
                           <PlateNumber>
                              <xsl:value-of select="PlateNumber"/>
                           </PlateNumber>
                           <Quantity>
                              <xsl:value-of select="Quantity"/>
                           </Quantity>
                           <IFS_Release_Nr>
                              <xsl:value-of select="IFS_Release_Nr"/>
                           </IFS_Release_Nr>
                           <Weight>
                              <xsl:value-of select="Weight"/>
                           </Weight>
                           <ReceivedWeight>
                              <xsl:value-of select="ReceivedWeight"/>
                           </ReceivedWeight>
                           <ReceivingDate>
                              <xsl:value-of select="ReceivingDate"/>
                           </ReceivingDate>
                           <HeatNo>
                              <xsl:value-of select="HeatNo"/>
                           </HeatNo>
                           <Length>
                              <xsl:value-of select="Length"/>
                           </Length>
                           <Width>
                              <xsl:value-of select="Width"/>
                           </Width>
                           <Info>
                              <xsl:value-of select="Info"/>
                           </Info>
                           <CertificateType>
                              <xsl:value-of select="CertificateType"/>
                           </CertificateType>
                           <CertificateNumber>
                              <xsl:value-of select="CertificateNumber"/>
                           </CertificateNumber>
                           <CarbonEquivalent>
                              <xsl:value-of select="CarbonEquivalent"/>
                           </CarbonEquivalent>
                           <SurfaceTreatment>
                              <xsl:value-of select="SurfaceTreatment"/>
                           </SurfaceTreatment>
                           <CoatingCertificate>
                              <xsl:value-of select="CoatingCertificate"/>
                           </CoatingCertificate>
                           <MechanicalTest>
                              <xsl:value-of select="MechanicalTest"/>
                           </MechanicalTest>
                        </Profile>
                     </xsl:for-each>
                  </PurchaseOrderLine>
               </xsl:for-each>
            </PurchaseOrder>
         </xsl:for-each>
      </Root>
   </xsl:template>
</xsl:stylesheet>
