<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://xmlns.oracle.com/IHC/OPSInventLabelSchema" xmlns:client="http://xmlns.oracle.com/IHC/OPSInventLabel" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl xsd soap wsdl ns1 client bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../OPSInventLabel.wsdl"/>
            <oracle-xsl-mapper:rootElement name="POReceipt" namespace="http://xmlns.oracle.com/IHC/OPSInventLabelSchema"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../OPSInventLabel.wsdl"/>
            <oracle-xsl-mapper:rootElement name="POReceipt" namespace="http://xmlns.oracle.com/IHC/OPSInventLabelSchema"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON JAN 14 13:33:32 CET 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:POReceipt>
      <ns1:Company>
        <xsl:value-of select="/POReceipt/Company"/>
      </ns1:Company>
      <ns1:Site>
        <xsl:value-of select="/POReceipt/Site"/>
      </ns1:Site>
      <ns1:PoNumber>
        <xsl:value-of select="/POReceipt/PoNumber"/>
      </ns1:PoNumber>
      <ns1:PoLineNo>
        <xsl:value-of select="/POReceipt/PoLineNo"/>
      </ns1:PoLineNo>
      <ns1:PoLineReleaseNo>
        <xsl:value-of select="/POReceipt/PoLineReleaseNo"/>
      </ns1:PoLineReleaseNo>
      <ns1:PoLineDescription>
        <xsl:value-of select="/POReceipt/PoLineDescription"/>
      </ns1:PoLineDescription>
      <ns1:PartNo>
        <xsl:value-of select="/POReceipt/PartNo"/>
      </ns1:PartNo>
      <ns1:Supplier>
        <xsl:value-of select="/POReceipt/Supplier"/>
      </ns1:Supplier>
      <ns1:SuppplierName>
        <xsl:value-of select="/POReceipt/SuppplierName"/>
      </ns1:SuppplierName>
      <ns1:QuantityReceived>
        <xsl:value-of select="/POReceipt/QuantityReceived"/>
      </ns1:QuantityReceived>
      <ns1:PurchUoM>
        <xsl:value-of select="/POReceipt/PurchUoM"/>
      </ns1:PurchUoM>
      <ns1:OrderRef1>
        <xsl:value-of select="/POReceipt/OrderRef1"/>
      </ns1:OrderRef1>
      <ns1:IHCProjectId>
        <xsl:value-of select="/POReceipt/IHCProjectId"/>
      </ns1:IHCProjectId>
      <ns1:IHCProjectDescription>
        <xsl:value-of select="/POReceipt/IHCProjectDescription"/>
      </ns1:IHCProjectDescription>
      <ns1:SubProjectId>
        <xsl:value-of select="/POReceipt/SubProjectId"/>
      </ns1:SubProjectId>
      <ns1:SubProjectIdName>
        <xsl:value-of select="/POReceipt/SubProjectIdName"/>
      </ns1:SubProjectIdName>
      <ns1:WBSElementId>
        <xsl:value-of select="/POReceipt/WBSElementId"/>
      </ns1:WBSElementId>
      <ns1:WBSElementDescription>
        <xsl:value-of select="/POReceipt/WBSElementDescription"/>
      </ns1:WBSElementDescription>
      <ns1:ActivityId>
        <xsl:value-of select="/POReceipt/ActivityId"/>
      </ns1:ActivityId>
      <ns1:ActivityDescription>
        <xsl:value-of select="/POReceipt/ActivityDescription"/>
      </ns1:ActivityDescription>
      <ns1:ActivitySequence>
        <xsl:value-of select="/POReceipt/ActivitySequence"/>
      </ns1:ActivitySequence>
      <ns1:ActualDeliveryDate>
        <xsl:value-of select="/POReceipt/ActualDeliveryDate"/>
      </ns1:ActualDeliveryDate>
      <ns1:UserId>
        <xsl:value-of select="/POReceipt/UserId"/>
      </ns1:UserId>
       <ns1:CIhcPrinter>
        <xsl:value-of select="/POReceipt/CIhcPrinter"/>
      </ns1:CIhcPrinter>
      <ns1:CreationDate>
        <xsl:value-of select="/POReceipt/CreationDate"/>
      </ns1:CreationDate>
      <ns1:ObjectId>
        <xsl:value-of select="/POReceipt/ObjectId"/>
      </ns1:ObjectId>
      <ns1:ObjectDescription>
        <xsl:value-of select="/POReceipt/ObjectDescription"/>
      </ns1:ObjectDescription>
      <ns1:waiv_dev_rej_no>
        <xsl:value-of select="/POReceipt/waiv_dev_rej_no"/>
      </ns1:waiv_dev_rej_no>
    </ns1:POReceipt>
  </xsl:template>
</xsl:stylesheet>