<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/IFSPurchaseOrderDbAdapter"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IHC/IFSPurchaseOrderUpdateService/IFSPurchaseOrderDbAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.oracle.com/IHC/IFSPurchaseOrderUpdateService/NestixPOUpdateService">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/IFSPurchaseOrderDbAdapter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CPurchaseInfoCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/IFSPurchaseOrderDbAdapter"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/NestixPOUpdateService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Root" namespace=""/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI MAY 24 11:00:41 CEST 2019].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <Root>
      <MsgSeqNo>
        <xsl:value-of select="substring(oraext:generate-guid ( ),1,10)"/>
      </MsgSeqNo>
      <Sender>IFS</Sender>
      <DateTime>
        <xsl:value-of select="xp20:current-dateTime ( )"/>
      </DateTime>
      <PurchaseOrder>
        <IFS_PONumber>
          <xsl:value-of select="/ns0:CPurchaseInfoCollection/ns0:CPurchaseInfo/ns0:orderNo"/>
        </IFS_PONumber>
        <SPx_PONumber>
          <xsl:value-of select="/ns0:CPurchaseInfoCollection/ns0:CPurchaseInfo/ns0:cExternalPoNo"/>
        </SPx_PONumber>
        <xsl:for-each select="/ns0:CPurchaseInfoCollection/ns0:CPurchaseInfo">
          <PurchaseOrderLine>
            <IFS_POLNumber>
              <xsl:value-of select="ns0:lineNo"/>
            </IFS_POLNumber>
            <SPx_POLNumber>
              <xsl:value-of select="ns0:cExternalPoLineNo"/>
            </SPx_POLNumber>
            <IFS_Status>
              <xsl:value-of select="ns0:status"/>
            </IFS_Status>
            <xsl:choose>
              <xsl:when test="string-length(ns0:cWidth) > 0">
                <Plate>
                  <ProjectNumber>
                    <xsl:value-of select="ns0:plant"/>
                  </ProjectNumber>
                  <Nestix_Section_ID>
                    <xsl:value-of select="ns0:cNestixSectionId"/>
                  </Nestix_Section_ID>
                  <Nestix_Du_ID>
                    <xsl:value-of select="ns0:cNestixDuId"/>
                  </Nestix_Du_ID>
                  <ArticleNumber>
                    <xsl:value-of select="ns0:partNo"/>
                  </ArticleNumber>
                  <WantedDeliveryDate>
                    <xsl:value-of select="substring-before(ns0:wantedDeliveryDate,'T')"/>
                  </WantedDeliveryDate>
                  <PlateNumber>
                    <xsl:value-of select="ns0:cPlateNumbers"/>
                  </PlateNumber>
                  <Quantity>
                    <!--<xsl:value-of select="ns0:External_Quantity"/>-->
                    <xsl:value-of select="ns0:cInterfacedQty"/>
                  </Quantity>
                  <Weight>
                    <xsl:value-of select="ns0:cTotalWeight"/>
                  </Weight>
                  <Length>
                    <xsl:value-of select="ns0:cLength"/>
                  </Length>
                  <Width>
                    <xsl:value-of select="ns0:cWidth"/>
                  </Width>
                  <IFS_Release_Nr>
                    <xsl:value-of select="ns0:releaseNo"/>
                  </IFS_Release_Nr>
                  <Price>
                    <xsl:value-of select="ns0:buyUnitPrice"/>
                  </Price>
                  <Currency_Code>
                    <xsl:value-of select="ns0:currencyCode"/>
                  </Currency_Code>
                  <Supplier>
                    <xsl:value-of select="ns0:vendorName"/>
                  </Supplier>
                  <ExpectedDeliveryDate>
                    <xsl:value-of select="substring-before(ns0:plannedReceiptDate,'T')"/>
                  </ExpectedDeliveryDate>
                </Plate>
              </xsl:when>
              <xsl:otherwise>
                <Profile>
                  <ProjectNumber>
                    <xsl:value-of select="ns0:plant"/>
                  </ProjectNumber>
                  <Nestix_Section_ID>
                    <xsl:value-of select="ns0:cNestixSectionId"/>
                  </Nestix_Section_ID>
                  <Nestix_Du_ID>
                    <xsl:value-of select="ns0:cNestixDuId"/>
                  </Nestix_Du_ID>
                  <ArticleNumber>
                    <xsl:value-of select="ns0:partNo"/>
                  </ArticleNumber>
                  <WantedDeliveryDate>
                    <xsl:value-of select="substring-before(ns0:wantedDeliveryDate,'T')"/>
                  </WantedDeliveryDate>
                  <PlateNumber>
                    <xsl:value-of select="ns0:cPlateNumbers"/>
                  </PlateNumber>
                  <Quantity>
                    <!--<xsl:value-of select="ns0:External_Quantity"/>-->
                    <xsl:value-of select="ns0:cInterfacedQty"/>
                  </Quantity>
                  <Weight>
                    <xsl:value-of select="ns0:cTotalWeight"/>
                  </Weight>
                  <Length>
                    <xsl:value-of select="ns0:cLength"/>
                  </Length>
                  <Width>
                    <xsl:value-of select="ns0:cWidth"/>
                  </Width>
                  <IFS_Release_Nr>
                    <xsl:value-of select="ns0:releaseNo"/>
                  </IFS_Release_Nr>
                  <Price>
                    <xsl:value-of select="ns0:buyUnitPrice"/>
                  </Price>
                  <Currency_Code>
                    <xsl:value-of select="ns0:currencyCode"/>
                  </Currency_Code>
                  <Supplier>
                    <xsl:value-of select="ns0:vendorName"/>
                  </Supplier>
                  <ExpectedDeliveryDate>
                    <xsl:value-of select="substring-before(ns0:plannedReceiptDate,'T')"/>
                  </ExpectedDeliveryDate>               
                </Profile>
              </xsl:otherwise>
            </xsl:choose>
          </PurchaseOrderLine>
        </xsl:for-each>
      </PurchaseOrder>
    </Root>
  </xsl:template>
</xsl:stylesheet>
